### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Kuchiru** [CupCakeArmy/volta#2]
So i think the app is great for what it does but has a few bugs, mostly polish i guess.

So here is what i've encountered so far.

1)
The icon does not play well with dark mode, its basically invisible.

2)
Set one application to full screen mode, open the app in the menu, close the window, Activate the desktop next to the full screen app and click to open the app in the menu again.
This will return you  to the desktop where you originally opened the app first.

**Comment by daaanny90** [comment]
Dark mode bug is now[ fixed ](https://github.com/cupcakearmy/volta/pull/3)
